CREATE TABLE demo (
    id                 VARCHAR(36) NOT NULL,
    ts                 VARCHAR(50) DEFAULT NULL,
    unitid             VARCHAR(1000) DEFAULT NULL,
    name               VARCHAR(50) DEFAULT NULL,
    ly_sm              VARCHAR(50) DEFAULT NULL,
    jfyq               VARCHAR(50) DEFAULT NULL,
    zy_cd              VARCHAR(50) DEFAULT NULL,
    create_time        VARCHAR(50) DEFAULT NULL,
    code               VARCHAR(50) DEFAULT NULL,
    begin_date         VARCHAR(50) DEFAULT NULL,
    kpi_level          VARCHAR(50) DEFAULT NULL,
    jd_bl              DECIMAL(28, 8) DEFAULT NULL,
    rwpf               DECIMAL(28, 3) DEFAULT NULL,
    update_name        VARCHAR(36) DEFAULT NULL,
    zrr                VARCHAR(500) DEFAULT NULL,
    dbr                VARCHAR(50) DEFAULT NULL,
    create_name        VARCHAR(36) DEFAULT NULL,
    xbr                VARCHAR(500) DEFAULT NULL,
    state              VARCHAR(50) DEFAULT NULL,
    zr_dw              VARCHAR(36) DEFAULT NULL,
    update_time        VARCHAR(50) DEFAULT NULL,
    end_date           VARCHAR(50) DEFAULT NULL,
    ly_code            VARCHAR(50) DEFAULT NULL,
    db_info            VARCHAR(50) DEFAULT NULL,
    xb_dw              VARCHAR(500) DEFAULT NULL,
    kpi_flag           VARCHAR(65) DEFAULT NULL,
    tenant_id          VARCHAR(50) DEFAULT NULL,
    qt_ld              VARCHAR(50) DEFAULT NULL,
    zbr                VARCHAR(500) DEFAULT NULL,
    dr                 INT DEFAULT NULL,
    create_user        VARCHAR(64) DEFAULT NULL,
    last_modified      VARCHAR(64) DEFAULT NULL,
    last_modify_user   VARCHAR(64) DEFAULT NULL,
    bpm_state          NUMBER(18, 2) DEFAULT NULL
);

CREATE TABLE demo_sub (
    id                    VARCHAR(36) NOT NULL,
    name                  VARCHAR(50) DEFAULT NULL,
    tenant_id             VARCHAR(50) DEFAULT NULL,
    update_time           VARCHAR(50) DEFAULT NULL,
    sub_name              VARCHAR(50) DEFAULT NULL,
    update_name           VARCHAR(36) DEFAULT NULL,
    sub_id                VARCHAR(36) DEFAULT '',
    create_time           VARCHAR(50) DEFAULT NULL,
    create_name           VARCHAR(36) DEFAULT NULL,
    begin_date            VARCHAR(50) DEFAULT NULL,
    sub_ms                VARCHAR(200) DEFAULT NULL,
    end_date              VARCHAR(50) DEFAULT NULL,
    sub_code              VARCHAR(50) DEFAULT NULL,
    fk_id_ygdemo_yw_sub   VARCHAR(36) DEFAULT NULL,
    zbr                   VARCHAR(50) DEFAULT NULL,
    ts                    VARCHAR(50) DEFAULT NULL,
    dr                    INT DEFAULT NULL,
    create_user           VARCHAR(64) DEFAULT NULL,
    last_modified         VARCHAR(64) DEFAULT NULL,
    last_modify_user      VARCHAR(64) DEFAULT NULL,
    bpm_state             INT DEFAULT NULL
);